version: "3.7"
services:
  frontend:
    build:
      context: frontend/docker/develop/nginx
    ports:
    - "${PORT_FRONT}:80"
    volumes:
    - ./frontend:/app

  api:
    build:
      context: api/docker/develop/nginx
    ports:
    - "${PORT_API}:80"
    volumes:
    - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker/develop/php-fpm
    volumes:
    - ./api:/app
